#!/usr/bin/env python3
"""Generate src/pet_balance_generated.h from balance.yaml.

Two invocation modes:
  1. PlatformIO pre-build:  Import("env") is available; we use env["PROJECT_DIR"]
     to locate balance.yaml.
  2. Standalone:            python3 gen_balance_h.py --yaml PATH --out PATH

Stdlib only — no PyYAML dependency. The YAML subset we parse:
  - Two-space nested mappings (top → group → scalar OR top → scalar)
  - Scalars: int, float, or double-quoted string
  - Comments: # to end-of-line
  - '#' characters are NOT allowed inside scalar values (parser strips them as comments)
  - Blank lines ignored
"""
import argparse
import os
import re
import sys
import tempfile
import time

# Constants that map flat dotted YAML paths to legacy #define names so firmware
# keeps using the names it already references. New constants get path-flattened
# uppercase names automatically.
LEGACY_NAMES = {
    "xp.per_session_ctx_pct": "XP_PER_SESSION_CTX_PCT",
    "xp.per_5h_pct":          "XP_PER_5H_PCT",
    "xp.per_weekly_pct":      "XP_PER_WEEKLY_PCT",
    "pet.max_level":          "PET_MAX_LEVEL",
    "pet.nvs_flush_interval_sec": "PET_NVS_FLUSH_INTERVAL",
    "pet.gallery_cap":        "PET_GALLERY_CAP",
    "pet.num_species":        "PET_NUM_SPECIES",
    "care.decay_interval_sec": "STAT_DECAY_INTERVAL",
    "care.action_refill_amount": "ACTION_REFILL_AMOUNT",
    "care.action_cooldown_sec": "ACTION_COOLDOWN_SEC",
    "care.sad_threshold":     "SAD_STAT_THRESHOLD",
    "care.neglect_rearm_threshold": "NEGLECT_REARM_THRESHOLD",
    "speech.neglect_min_pet_age_sec": "NEGLECT_MIN_PET_AGE_SEC",
    "speech.neglect_absence_sec": "NEGLECT_ABSENCE_SEC",
    "vacation.max_days":      "VACATION_MAX_DAYS",
}


def parse_yaml(text):
    """Tiny YAML reader. Returns nested dict. Raises ValueError on unsupported input."""
    result = {}
    current_group = None
    current_key = None
    for lineno, raw_line in enumerate(text.splitlines(), start=1):
        # Strip comments and trailing whitespace
        line = re.sub(r"#.*$", "", raw_line).rstrip()
        if not line.strip():
            continue
        # Detect indent (must be 0 or 2 spaces)
        m = re.match(r"^([ \t]*)(.*)$", line)
        if "\t" in m.group(1):
            raise ValueError(f"line {lineno}: tabs not allowed in indent")
        indent = len(m.group(1))
        body = m.group(2)
        if indent == 0:
            # Top-level: must end with ':' (group header) or be 'key: scalar'
            if body.endswith(":"):
                current_group = body[:-1].strip()
                if current_group in result:
                    raise ValueError(f"line {lineno}: duplicate key: {current_group!r}")
                result[current_group] = {}
            elif ":" in body:
                k, _, v = body.partition(":")
                key = k.strip()
                if key in result:
                    raise ValueError(f"line {lineno}: duplicate key: {key!r}")
                result[key] = parse_scalar(v.strip(), lineno)
                current_group = None
            else:
                raise ValueError(f"line {lineno}: cannot parse top-level: {raw_line!r}")
        elif indent == 2:
            if current_group is None:
                raise ValueError(f"line {lineno}: indented line with no parent group: {raw_line!r}")
            if ":" not in body:
                raise ValueError(f"line {lineno}: expected key:value under group: {raw_line!r}")
            k, _, v = body.partition(":")
            key = k.strip()
            if key in result[current_group]:
                raise ValueError(f"line {lineno}: duplicate key: {key!r}")
            result[current_group][key] = parse_scalar(v.strip(), lineno)
        else:
            raise ValueError(f"line {lineno}: unexpected indent {indent}: {raw_line!r}")
    return result


def parse_scalar(s, lineno):
    """Parse an int, float, or double-quoted string."""
    if not s:
        raise ValueError(f"line {lineno}: empty scalar value")
    if s[0] == '"' and s[-1] == '"':
        return s[1:-1]
    # Try int first (so "5" → 5, not 5.0)
    try:
        return int(s)
    except ValueError:
        pass
    try:
        return float(s)
    except ValueError:
        pass
    raise ValueError(f"line {lineno}: cannot parse scalar (not int/float/quoted string): {s!r}")


def format_scalar(v):
    """C literal for a scalar value."""
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        return repr(v)   # 1.05 → "1.05"
    if isinstance(v, str):
        return f'"{v}"'
    raise TypeError(f"unsupported scalar type: {type(v).__name__}")


def emit_header(data, source_path):
    """Format the generated header text."""
    out = []
    out.append("// Auto-generated by firmware/scripts/gen_balance_h.py")
    out.append(f"// Source: {os.path.relpath(source_path)}")
    out.append(f"// Generated: {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime())}")
    out.append("// DO NOT EDIT — change firmware/balance.yaml and rebuild.")
    out.append("#pragma once")
    out.append("")
    for top_key, top_val in data.items():
        if isinstance(top_val, dict):
            out.append(f"// ---- {top_key} ----")
            for sub_key, sub_val in top_val.items():
                dotted = f"{top_key}.{sub_key}"
                name = LEGACY_NAMES.get(dotted, dotted.upper().replace(".", "_"))
                out.append(f"#define {name} {format_scalar(sub_val)}")
            out.append("")
        else:
            name = LEGACY_NAMES.get(top_key, top_key.upper())
            out.append(f"#define {name} {format_scalar(top_val)}")
    return "\n".join(out) + "\n"


def atomic_write(path, content):
    """Write to a temp file in the same dir and rename — atomic on POSIX."""
    dest_dir = os.path.dirname(path) or "."
    fd, tmp = tempfile.mkstemp(prefix=".pet_balance_", dir=dest_dir)
    try:
        with os.fdopen(fd, "w") as f:
            f.write(content)
        os.replace(tmp, path)
    except Exception:
        try: os.unlink(tmp)
        except OSError: pass
        raise


def generate(yaml_path, out_path):
    with open(yaml_path) as f:
        data = parse_yaml(f.read())
    content = emit_header(data, yaml_path)
    # Skip rewrite if the file hasn't changed (don't invalidate ccache).
    if os.path.exists(out_path):
        with open(out_path) as f:
            if f.read() == content:
                return False
    atomic_write(out_path, content)
    return True


def main_standalone():
    ap = argparse.ArgumentParser()
    ap.add_argument("--yaml", required=True)
    ap.add_argument("--out",  required=True)
    args = ap.parse_args()
    try:
        changed = generate(args.yaml, args.out)
    except (OSError, ValueError) as e:
        print(f"gen_balance_h: ERROR: {e}", file=sys.stderr)
        sys.exit(1)
    print(f"gen_balance_h: {'wrote' if changed else 'unchanged'} {os.path.relpath(args.out)}")


# PlatformIO pre-script entry point — runs when the file is imported by SCons.
try:
    Import("env")  # type: ignore[name-defined]   # noqa: F821
    PROJECT_DIR = env["PROJECT_DIR"]  # type: ignore[name-defined]  # noqa: F821
    yaml_path = os.path.join(PROJECT_DIR, "balance.yaml")
    out_path = os.path.join(PROJECT_DIR, "src", "pet_balance_generated.h")
    try:
        changed = generate(yaml_path, out_path)
        print(f"gen_balance_h: {'wrote' if changed else 'unchanged'} src/pet_balance_generated.h")
    except (OSError, ValueError) as e:
        print(f"gen_balance_h: ERROR: {e}", file=sys.stderr)
        sys.exit(1)
except NameError:
    # Not inside PlatformIO — run in standalone mode if invoked directly.
    if __name__ == "__main__":
        main_standalone()
